name: Mingledxb
description: Flutter Mingledxb Application

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons:

  firebase_core: ^2.7.1
  firebase_auth: ^4.2.9
  cloud_firestore: ^4.4.0
  firebase_messaging: ^14.2.2
  firebase_storage: ^11.0.11
  google_mobile_ads: ^2.3.0
  in_app_purchase: ^3.1.1
  flutter_svg: 1.1.6
  flutter_launcher_icons: 0.11.0
  flutter_native_splash: 2.2.16
  country_code_picker: 2.0.2
  scoped_model: 2.0.0
  image_picker: 0.8.6+1
  image_cropper: 3.0.1
  url_launcher: ^6.1.9
  geolocator: 9.0.2
  geocoding: 2.0.5
  rxdart: 0.27.3
  shimmer: 2.0.0
  timeago:
  share: ^2.0.4
  flutter_cupertino_datetime_picker: 3.0.0
  place_picker: 0.10.0
  fluttertoast: 8.1.3
  google_sign_in: ^6.0.2
  simple_circular_progress_bar: ^1.0.2

dependency_overrides:
  modal_bottom_sheet: ^3.0.0-pre

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.11.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/lang/
    - assets/interest/

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.jpg"
  adaptive_icon_padding: true
  adaptive_icon_foreground: "assets/images/app_logo.jpg"
  adaptive_icon_background: "#ed1e79"
  


flutter_native_splash:
  color: "#000000"
  image: "assets/images/app_logo.jpeg"
  android: true
  ios: true
